[game]
name = "Tetris Attack"
shiftTableBy = 16

[game.encoding]
table = [
    { offset = 0x00, glyphs = [
        # Aren't these variable width?
        # HALF-WIDTH NUMBERS
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", 

        # HALF-WIDTH ALPHABET
        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", 
        "S", "T", "U", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", 
        "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",

        # HALF-WIDTH PUNCTUATION
        "-", "!", "?", "·", ":", ";", ",", "(", ")", ".", "'", "\""
    ]},
    { offset = 0xB0, glyphs = [
        # FULL-WIDTH NUMBERS
        "０", "１", "２", "３", "４", "５", "６", "７", "８", "９",

        # FULL-WIDTH ALPHABET
        "Ａ", "Ｂ", "Ｃ", "Ｄ", "Ｅ", "Ｆ", "Ｇ", "Ｈ", "Ｉ", "Ｊ", "Ｋ", "Ｌ", "Ｍ", "Ｎ", "Ｏ", "Ｐ", 
        "Ｑ", "Ｒ", "Ｓ", "Ｔ", "Ｕ", "Ｖ", "Ｗ", "Ｘ", "Ｙ", "Ｚ", "ａ", "ｂ", "ｃ", "ｄ", "ｅ", "ｆ", 
        "ｇ", "ｈ", "ｉ", "ｊ", "ｋ", "ｌ", "ｍ", "ｎ", "ｏ", "ｐ", "ｑ", "ｒ", "ｓ", "ｔ", "ｕ", "ｖ", 
        "ｗ", "ｘ", "ｙ", "ｚ"
    ]},
    { offset= 0xFA, glyphs = [
        # HIRAGANA
        "あ", "い", "う", "え", "お", "か", "き", "く", "け", "こ", "さ", "し", "す", "せ", "そ", "た", 
        "ち", "つ", "て", "と", "な", "に", "ぬ", "ね", "の", "は", "ひ", "ふ", "へ", "ほ", "ま", "み", 
        "む", "め", "も", "や", "ゆ", "よ", "ら", "り", "る", "れ", "ろ", "わ", "を", "ん", "が", "ぎ", 
        "ぐ", "げ", "ご", "ざ", "じ", "ず", "ぜ", "ぞ", "だ", "ぢ", "づ", "で", "ど", "ば", "び", "ぶ", 
        "べ", "ぼ", "ぱ", "ぴ", "ぷ", "ぺ", "ぽ", "ぁ", "ぃ", "ぅ", "ぇ", "ぉ", "ゃ", "ゅ", "ょ", "っ",

        # KATAKANA 
        "ア", "イ", "ウ", "エ", "オ", "カ", "キ", "ク", "ケ", "コ", "サ", "シ", "ス", "セ", "ソ", "タ", "チ", "ツ", "テ", "ト", "ナ", "ニ", "ヌ", "ネ", "ノ", "ハ", "ヒ", "フ", "ヘ", "ホ", "マ", "ミ", "ム", "メ", "モ", "ヤ", "ユ", "ヨ", "ラ", "リ", "ル", "レ", "ロ", "ワ", "ヲ", "ン", "ガ", "ギ", "グ", "ゲ", "ゴ", "ザ", "ジ", "ズ", "ゼ", "ゾ", "ダ", "ヂ", "ヅ", "デ", "ド", "バ", "ビ", "ブ", "ベ", "ボ", "パ", "ピ", "プ", "ペ", "ポ", "ァ", "ィ", "ゥ", "ェ", "ォ", "ャ", "ュ", "ョ", "ッ", "ヴ"
    ]}
]

[game.encoding.controls]
C4 = { name = "unknown3", length = 4 }
C8 = { name = "table", length = 1 }
D3 = { name = "unknown1", length = 3 }
DB = { name = "goto", length = 2 }
E0 = { name = "waitInput", length = 0 }
E1 = { name = "sleep1", length = 0 }
E2 = { name = "sleep2", length = 0 }
E3 = { name = "sleep3", length = 0 }
E4 = { name = "sleep4", length = 0 }
E5 = { name = "sleep5", length = 0 }
E6 = { name = "sleep6", length = 0 }
EF = { name = "unknown2", length = 0 }
F1 = { name = "⠀" }                         # Why     there     spaces
F2 = { name = " " }                         #     are       two
F4 = { name = "setSpaceWidth", length = 1 }
F5 = { name = "clear", length = 0 }
F6 = { name = "indent", length = 1 }
F8 = { name = "textbox", length = 4 }
F9 = { name = "speed", length = 1 }
FB = { name = "color", length = 1 }
FD = { name = "\n" }
FE = { name = "playNextStep", length = 0 }
